"""Deterministic seed generator, --seed 42, byte-identical across runs.

Plants exactly 7 violations (~$23,400) per architecture.md section 10.
Everything else is generated to stay clean under every rule -- amounts
under R6 thresholds, budgets generously funded except the one engineered
Q2 marketing breach, no accidental R4 near-duplicate pairs, warrants
scoped/ceilinged with margin except the one engineered expiry.

Do not edit this file except to fix a planted violation -- CLAUDE.md.
"""
from __future__ import annotations

import argparse
import random
from datetime import date, datetime, timedelta

from fallback.db import connect, dumps, init_db, new_id, reset_db

CATEGORIES = [
    "infrastructure", "software", "legal", "contractor",
    "marketing", "travel", "hardware", "other",
]
# R6's soft-threshold category set (amount cap for the clean-transaction loop).
SOFT_THRESHOLD_CATEGORIES = {"legal", "contractor", "marketing"}
# W2/W2b's warrant scope -- a different set from R6's; travel is warrant-restricted
# but has no R6 soft threshold. Conflating the two sets caused clean 'travel'
# transactions to be assigned warrant W1, which doesn't cover 'travel' (R1
# WARRANT_CATEGORY_OUT_OF_SCOPE false positive).
WARRANT2_CATEGORIES = {"legal", "contractor", "marketing", "travel"}
# 'marketing' is excluded from the random clean loop entirely: all marketing
# spend is deliberately engineered by the V3 budget-breach sequence below, so
# random marketing transactions can't bleed into that budget bucket.
CLEAN_LOOP_CATEGORIES = [c for c in CATEGORIES if c != "marketing"]
SOFT_THRESHOLD_CENTS = 200_000
HARD_THRESHOLD_CENTS = 500_000

DATASET_START = date(2026, 2, 1)
DATASET_END = date(2026, 7, 31)

VENDOR_POOL = [
    ("ACME Cloud Services LLC", "infrastructure"),
    ("Northgate Analytics Suite", "software"),
    ("Halberd Consulting Group", "contractor"),
    ("Titan Hardware Solutions", "hardware"),
    ("Meridian Legal Partners", "legal"),
    ("Bluewave Media Agency", "marketing"),
    ("Skyline Travel Bureau", "travel"),
    ("Fabrikam Office Supplies", "other"),
    ("Contoso Data Systems", "infrastructure"),
    ("Initech Dev Tools", "software"),
    ("Umbrella Compliance Advisors", "legal"),
    ("Globex Freight & Logistics", "other"),
    ("Stark Component Works", "hardware"),
    ("Wayne Facilities Group", "other"),
    ("Aperture Research Labs", "software"),
    ("Cyberdyne Infra Systems", "infrastructure"),
    ("Soylent Catering Co", "other"),
    ("Hooli Cloud Platform", "infrastructure"),
    ("Vandelay Import Export", "other"),
    ("Pied Piper Compression", "software"),
    ("Massive Dynamic Labs", "hardware"),
    ("Gringotts Financial Advisors", "legal"),
    ("Oceanic Airlines Corporate", "travel"),
    ("Prestige Worldwide Marketing", "marketing"),
    ("Dunder Mifflin Paper Co", "other"),
    ("Sterling Cooper Advertising", "marketing"),
    ("Wonka Industrial Supply", "hardware"),
    ("Monsters Inc Facilities", "other"),
    ("Nakatomi Trading Corp", "contractor"),
    ("Genco Import/Export", "other"),
]

QUARTERS = [
    ("2026-01-01", "2026-03-31"),
    ("2026-04-01", "2026-06-30"),
    ("2026-07-01", "2026-09-30"),
]
DEFAULT_BUDGET_CENTS = 30_000_000  # $300,000/quarter -- comfortably above realistic random-clean volume
MARKETING_Q2_BUDGET_CENTS = 2_000_000  # $20,000, deliberately tight for V3


def daterange_days(start: date, end: date) -> list[date]:
    days = (end - start).days
    return [start + timedelta(days=i) for i in range(days + 1)]


class DuplicateGuard:
    """Rejects clean-transaction candidates that would accidentally trip R4."""

    def __init__(self):
        # vendor_name -> list of (date, amount_cents, category)
        self.by_vendor: dict[str, list[tuple[date, int, str]]] = {}

    def collides(self, vendor_name: str, when: date, amount_cents: int, category: str) -> bool:
        for prior_date, prior_amount, prior_category in self.by_vendor.get(vendor_name, []):
            if prior_category != category:
                continue
            if abs((when - prior_date).days) > 30:
                continue
            if prior_amount <= 0:
                continue
            if abs(amount_cents - prior_amount) / prior_amount <= 0.05:
                return True
        return False

    def record(self, vendor_name: str, when: date, amount_cents: int, category: str) -> None:
        self.by_vendor.setdefault(vendor_name, []).append((when, amount_cents, category))


class VelocityGuard:
    """Rejects clean-transaction candidates that would accidentally trip R5.

    Independently-random timestamps across ~180 days occasionally cluster
    within the same 10-minute window by chance (birthday-paradox style).
    Reject any candidate within 10 minutes of an existing timestamp for the
    same agent instead of letting that happen.
    """

    def __init__(self):
        self.by_agent: dict[str, list[datetime]] = {}

    def collides(self, agent_id: str, when: datetime) -> bool:
        return any(
            abs((when - existing).total_seconds()) < 600
            for existing in self.by_agent.get(agent_id, [])
        )

    def record(self, agent_id: str, when: datetime) -> None:
        self.by_agent.setdefault(agent_id, []).append(when)


def build(seed: int = 42, db_path: str | None = None) -> None:
    rng = random.Random(seed)
    reset_db(db_path)
    conn = connect(db_path)

    # -- principals --------------------------------------------------
    principals = [
        ("p_alice", "Alice Chen", "alice@orbis-demo.test", "finance_lead"),
        ("p_ben", "Ben Torres", "ben@orbis-demo.test", "engineering_lead"),
    ]
    conn.executemany("INSERT INTO principals VALUES (?,?,?,?)", principals)

    # -- agents --------------------------------------------------------
    agents = [
        ("agent_ops", "agent-ops", "p_alice", "local:agent-ops", "spender", None, "active"),
        ("agent_vendor", "agent-vendor", "p_ben", "local:agent-vendor", "payee", "wallet_agent_vendor", "active"),
        ("agent_runaway", "agent-runaway", "p_alice", "local:agent-runaway", "spender", None, "active"),
        ("agent_hostile", "agent-hostile", "p_alice", "local:agent-hostile", "spender", None, "active"),
    ]
    conn.executemany("INSERT INTO agents VALUES (?,?,?,?,?,?,?)", agents)

    # -- vendors -------------------------------------------------------
    vendor_ids: dict[str, str] = {}
    for name, _category in VENDOR_POOL:
        vid = new_id("v")
        vendor_ids[name] = vid
        conn.execute(
            "INSERT INTO vendors VALUES (?,?,?,?,?)",
            (vid, name, dumps([]), "approved", DATASET_START.isoformat()),
        )

    # -- warrants --------------------------------------------------------
    # W1: agent-ops, unrestricted-category-set warrant, spans the whole dataset.
    w1 = "w_ops_main"
    conn.execute(
        "INSERT INTO warrants VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (w1, "agent_ops", "p_alice", dumps(["infrastructure", "software", "hardware", "other"]),
         1_000_000, 60_000_000, 0, dumps(["*"]), dumps(["*"]),
         "2026-01-01", "2026-12-31", "active",
         "Alice authorizes agent-ops to spend on infrastructure, software, hardware, and other operating categories."),
    )
    # W2: agent-ops, restricted-category warrant, expires 2026-06-30 (feeds V7).
    w2 = "w_ops_restricted_h1"
    conn.execute(
        "INSERT INTO warrants VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (w2, "agent_ops", "p_alice", dumps(["legal", "contractor", "marketing", "travel"]),
         1_500_000, 30_000_000, 0, dumps(["*"]), dumps(["*"]),
         "2026-01-01", "2026-06-30", "active",
         "Alice authorizes agent-ops to spend on legal, contractor, marketing, and travel through end of Q2."),
    )
    # W2b: renewal of W2 for H2.
    w2b = "w_ops_restricted_h2"
    conn.execute(
        "INSERT INTO warrants VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (w2b, "agent_ops", "p_alice", dumps(["legal", "contractor", "marketing", "travel"]),
         1_500_000, 30_000_000, 0, dumps(["*"]), dumps(["*"]),
         "2026-07-01", "2026-12-31", "active",
         "Alice renews agent-ops's authorization for legal, contractor, marketing, and travel."),
    )
    # W3: agent-runaway, narrow infrastructure-only warrant.
    w3 = "w_runaway"
    conn.execute(
        "INSERT INTO warrants VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (w3, "agent_runaway", "p_alice", dumps(["infrastructure"]),
         200_000, 5_000_000, 0, dumps(["*"]), dumps(["*"]),
         "2026-01-01", "2026-12-31", "active",
         "Alice authorizes agent-runaway to spend on infrastructure top-ups."),
    )
    # W4: agent-hostile, narrow warrant for the live injection demo.
    w4 = "w_hostile"
    conn.execute(
        "INSERT INTO warrants VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (w4, "agent_hostile", "p_alice", dumps(["software", "infrastructure"]),
         200_000, 5_000_000, 0, dumps(["*"]), dumps(["*"]),
         "2026-01-01", "2026-12-31", "active",
         "Alice authorizes agent-hostile (vendor-invoice intake) to spend on software and infrastructure."),
    )

    # -- budgets: one row per (category, quarter) -----------------------
    budget_ids: dict[tuple[str, str], str] = {}
    for category in CATEGORIES:
        for q_start, q_end in QUARTERS:
            bid = new_id("b")
            budgeted = MARKETING_Q2_BUDGET_CENTS if (category == "marketing" and q_start == "2026-04-01") else DEFAULT_BUDGET_CENTS
            conn.execute(
                "INSERT INTO budgets VALUES (?,?,?,?,?,?)",
                (bid, category, q_start, q_end, budgeted, 0),
            )
            budget_ids[(category, q_start)] = bid

    conn.commit()

    guard = DuplicateGuard()
    velocity_guard = VelocityGuard()

    def warrant_for(category: str, when: date) -> str:
        if category in WARRANT2_CATEGORIES:
            return w2 if when <= date(2026, 6, 30) else w2b
        return w1

    def insert_txn(agent_id: str, warrant_id: str, vendor_name: str, category: str,
                    amount_cents: int, when: datetime, recurring: bool, purpose: str) -> str:
        sr_id = new_id("sr")
        txn_id = new_id("t")
        conn.execute(
            "INSERT INTO spend_requests VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (sr_id, agent_id, warrant_id, "bank", vendor_name, None, category,
             amount_cents, purpose, when.isoformat(), "executed"),
        )
        conn.execute(
            "INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (txn_id, "bank", vendor_ids[vendor_name], None, category, amount_cents,
             when.isoformat(), purpose, 1 if recurring else 0, f"pi_test_{txn_id}", sr_id),
        )
        velocity_guard.record(agent_id, when)
        return txn_id

    # Register the fixed violation timestamps for agent-ops up front so the
    # random clean loop below never places a lookalike request within 10
    # minutes of one of them.
    for fixed_when in (
        datetime(2026, 7, 2, 10, 0, 0), datetime(2026, 7, 13, 10, 5, 0),
        datetime(2026, 4, 6, 11, 0, 0), datetime(2026, 4, 25, 11, 30, 0),
        datetime(2026, 6, 25, 14, 0, 0), datetime(2026, 5, 20, 9, 30, 0),
        datetime(2026, 3, 10, 15, 0, 0), datetime(2026, 7, 4, 13, 0, 0),
    ):
        velocity_guard.record("agent_ops", fixed_when)

    # === Clean transaction generation ===================================
    purposes_by_category = {
        "infrastructure": "cloud hosting and infra services",
        "software": "software license renewal",
        "legal": "legal advisory services",
        "contractor": "contractor engagement",
        "marketing": "marketing campaign spend",
        "travel": "business travel booking",
        "hardware": "hardware procurement",
        "other": "general operating expense",
    }

    all_days = daterange_days(DATASET_START, DATASET_END)
    target_clean_count = 385
    generated = 0
    attempts = 0
    max_attempts = target_clean_count * 20

    while generated < target_clean_count and attempts < max_attempts:
        attempts += 1
        category = rng.choice(CLEAN_LOOP_CATEGORIES)
        candidates = [name for name, cat in VENDOR_POOL if cat == category] or [n for n, _ in VENDOR_POOL]
        vendor_name = rng.choice(candidates)
        when_date = rng.choice(all_days)
        when = datetime.combine(when_date, datetime.min.time()) + timedelta(
            hours=rng.randint(8, 18), minutes=rng.randint(0, 59)
        )

        cap = SOFT_THRESHOLD_CENTS if category in SOFT_THRESHOLD_CATEGORIES else HARD_THRESHOLD_CENTS
        amount_cents = rng.randint(3_000, int(cap * 0.85))

        if guard.collides(vendor_name, when_date, amount_cents, category):
            continue
        if velocity_guard.collides("agent_ops", when):
            continue

        warrant_id = warrant_for(category, when_date)
        insert_txn("agent_ops", warrant_id, vendor_name, category, amount_cents, when, False,
                   purposes_by_category[category])
        guard.record(vendor_name, when_date, amount_cents, category)
        generated += 1

    conn.commit()

    # === V1: hero duplicate =============================================
    # ACME Cloud Services LLC $4,080 (07-02, recurring) -> Accme Cloud Svcs
    # $4,200 (07-13, 11 days later). Misspelling lands the match in the
    # ambiguous [0.65, 0.90) band -- verified in tests/test_matcher.py.
    prior_when = datetime(2026, 7, 2, 10, 0, 0)
    insert_txn("agent_ops", w1, "ACME Cloud Services LLC", "infrastructure", 408_000,
               prior_when, True, "cloud hosting and infra services")
    guard.record("ACME Cloud Services LLC", prior_when.date(), 408_000, "infrastructure")

    dup_when = datetime(2026, 7, 13, 10, 5, 0)
    sr_dup = new_id("sr")
    t_dup = new_id("t")
    conn.execute(
        "INSERT INTO spend_requests VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        (sr_dup, "agent_ops", w1, "bank", "Accme Cloud Svcs", None, "infrastructure",
         420_000, "cloud hosting and infra services", dup_when.isoformat(), "executed"),
    )
    conn.execute(
        "INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        (t_dup, "bank", vendor_ids["ACME Cloud Services LLC"], None, "infrastructure", 420_000,
         dup_when.isoformat(), "cloud hosting and infra services", 0, f"pi_test_{t_dup}", sr_dup),
    )

    # === V2: non-recurring duplicate, 19 days apart, 3% amount diff =====
    v2_vendor = "Northgate Analytics Suite"
    v2_prior_when = datetime(2026, 4, 6, 11, 0, 0)
    insert_txn("agent_ops", w1, v2_vendor, "software", 200_000, v2_prior_when, False,
               "software license renewal")
    guard.record(v2_vendor, v2_prior_when.date(), 200_000, "software")

    v2_when = datetime(2026, 4, 25, 11, 30, 0)
    sr_v2 = new_id("sr")
    t_v2 = new_id("t")
    conn.execute(
        "INSERT INTO spend_requests VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        (sr_v2, "agent_ops", w1, "bank", v2_vendor, None, "software",
         206_000, "software license renewal", v2_when.isoformat(), "executed"),
    )
    conn.execute(
        "INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        (t_v2, "bank", vendor_ids[v2_vendor], None, "software", 206_000,
         v2_when.isoformat(), "software license renewal", 0, f"pi_test_{t_v2}", sr_v2),
    )

    # === V3: marketing budget breach, 148% of Q2 ========================
    # Steady spend to $17,000 committed (0.85 of $20,000, safely under the
    # 1.05 ROUTE threshold), then a single $12,600 transaction that jumps
    # straight past 1.20 to 1.48 -- no intermediate ROUTE-zone transaction.
    # Round-robin the full vendor pool (not just the 3 marketing-tagged
    # ones) so consecutive top-ups never land on the same vendor within
    # the 30-day/5% R4 window.
    q2_days = daterange_days(date(2026, 4, 1), date(2026, 6, 20))
    all_vendor_names = [n for n, _ in VENDOR_POOL]
    committed = 0
    step = 130_000  # ~$1,300 per top-up
    i = 0
    while committed < 1_700_000 and i < len(all_vendor_names) * 3:
        vendor_name = all_vendor_names[i % len(all_vendor_names)]
        when_date = q2_days[(i * 5) % len(q2_days)]
        when = datetime.combine(when_date, datetime.min.time()) + timedelta(hours=10 + i % 5)
        amount = min(step, 1_700_000 - committed)
        if amount < 50_000:
            amount = 50_000
        if guard.collides(vendor_name, when_date, amount, "marketing"):
            i += 1
            continue
        insert_txn("agent_ops", w2, vendor_name, "marketing", amount, when, False,
                   "marketing campaign spend")
        guard.record(vendor_name, when_date, amount, "marketing")
        committed += amount
        i += 1
    assert committed >= 1_700_000, f"V3 setup only reached {committed}c committed before giving up"

    v3_when = datetime(2026, 6, 25, 14, 0, 0)
    insert_txn("agent_ops", w2, "Prestige Worldwide Marketing", "marketing", 870_000, v3_when, False,
               "Q2 campaign push -- paid media placements")

    # === V4: unapproved vendor, never onboarded, $6,800 =================
    v4_when = datetime(2026, 5, 20, 9, 30, 0)
    sr_v4 = new_id("sr")
    conn.execute(
        "INSERT INTO spend_requests VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        (sr_v4, "agent_ops", w1, "bank", "Redwood Data Partners", None, "other",
         680_000, "one-off data enrichment vendor", v4_when.isoformat(), "executed"),
    )
    # No `vendors` row exists for Redwood Data Partners -- never onboarded.
    # vendor_id is nullable, so the ledger entry just records no resolved
    # vendor rather than inventing a decoy row that would pollute the
    # fuzzy-matcher's candidate pool with a near-identical name.
    t_v4 = new_id("t")
    conn.execute(
        "INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        (t_v4, "bank", None, None, "other", 680_000,
         v4_when.isoformat(), "one-off data enrichment vendor", 0, f"pi_test_{t_v4}", sr_v4),
    )

    # === V5: missing approval, above R6 hard threshold, no approval on file
    v5_when = datetime(2026, 3, 10, 15, 0, 0)
    insert_txn("agent_ops", w1, "Titan Hardware Solutions", "hardware", 530_000, v5_when, False,
               "bulk hardware refresh -- no human sign-off on file")
    guard.record("Titan Hardware Solutions", v5_when.date(), 530_000, "hardware")

    # === V6: velocity, 9 requests in 6 minutes ==========================
    burst_vendors = rng.sample([n for n, _ in VENDOR_POOL], 9)
    burst_start = datetime(2026, 5, 15, 10, 0, 0)
    for idx, vname in enumerate(burst_vendors):
        when = burst_start + timedelta(minutes=idx)
        amount = 1_000 + idx * 137
        if guard.collides(vname, when.date(), amount, "infrastructure"):
            amount += 500
        insert_txn("agent_runaway", w3, vname, "infrastructure", amount, when, False,
                   "burst infra top-up")
        guard.record(vname, when.date(), amount, "infrastructure")

    # === V7: expired warrant, charge 4 days after expiry ================
    v7_when = datetime(2026, 7, 4, 13, 0, 0)
    insert_txn("agent_ops", w2, "Halberd Consulting Group", "contractor", 190_000, v7_when, False,
               "contractor engagement -- stale warrant reference")
    guard.record("Halberd Consulting Group", v7_when.date(), 190_000, "contractor")

    conn.commit()

    # === Finalize live counters: warrants.spent_total_cents / budgets.committed_cents
    for wid in (w1, w2, w2b, w3, w4):
        row = conn.execute(
            """
            SELECT COALESCE(SUM(t.amount_cents), 0) AS total
            FROM transactions t JOIN spend_requests sr ON t.spend_request_id = sr.id
            WHERE sr.warrant_id = ?
            """,
            (wid,),
        ).fetchone()
        conn.execute("UPDATE warrants SET spent_total_cents = ? WHERE id = ?", (row["total"], wid))

    for (category, q_start), bid in budget_ids.items():
        q_end = next(e for s, e in QUARTERS if s == q_start)
        row = conn.execute(
            "SELECT COALESCE(SUM(amount_cents), 0) AS total FROM transactions "
            "WHERE category = ? AND occurred_at >= ? AND occurred_at <= ?",
            (category, q_start, q_end + "T23:59:59"),
        ).fetchone()
        conn.execute("UPDATE budgets SET committed_cents = ? WHERE id = ?", (row["total"], bid))

    conn.commit()
    conn.close()
    print(f"Seed complete: {generated} clean + 7 planted violations.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    build(seed=args.seed)
